name: dms-vep-pipeline-3

channels:
  - conda-forge
  - bioconda

dependencies:
  - altair=6.2.1
  - baltic=0.3
  - biopython=1.87
  - black-jupyter=26
  - entrez-direct=25
  - flatdict=4.1
  - git-lfs
  - jupyterlab
  - mafft=7.526
  - markdown=3.10
  - marimo=0.23
  - matplotlib=3.10
  - minimap2=2.31
  - nbstripout
  - openpyxl
  - pandas=2.3
  - papermill=2.7
  - pysam=0.24
  - pip
  - plotnine=0.15
  - pyarrow
  - python=3.13
  - ruamel.yaml=0.19
  - ruff=0.15
  - seaborn=0.13
  - snakefmt=2.0
  - snakemake=9.22
  - upsetplot=0.9
  - pip:
      - alignparse==0.8.0
      - dms_variants==1.4.3
      - dmslogo==0.7.1
      - multidms==0.4.2
      - neutcurve==2.3
      - polyclonal==6.17
